### ISSUE TITLE
V2: Nervos Docs V2 Project

### ISSUE THREAD

**Issue by roughpandaz** [nervosnetwork/docs.nervos.org#208]
## Context
It takes too many steps for 1st time devs to: test, build, and deploy DApps on CKB

## Goals:
**A first-time developer can quickly:**
1. Test, build, and deploy DApps (and Contracts)
2. Find any information and help

Good Dev Experiences: https://stripe.com/docs 

## Phase 1: Issue Tracker
**UI**
- [x] WireFrame: https://github.com/nervosnetwork/docs.nervos.org/issues/209 - (02/22 Thu)
- [x] High Fidelity
- [x] Implement UI on Docasarus

**DApp Examples**
- [x] Create 4 tutorials to teach developers how to get started building DApps: https://github.com/nervosnetwork/docs.nervos.org/issues/211 - 

**Dev Tools**
- [x] Short introduction to DApp development tools + link to these applications: Lumos, Kuai? https://github.com/nervosnetwork/docs.nervos.org/pull/242 
- [x] RPC endpoints: list the RFC endpoints and status. https://github.com/nervosnetwork/docs.nervos.org/pull/244

**Local Environment Setup**
- [x] Simplify Dev Env setup: https://github.com/nervosnetwork/docs.nervos.org/issues/210
- [x] Supported environment: Docker, Mac, Linux, (Windows)
- [x] Update Tutorial to configure local dev environment

**Ecosystem**
- [x] Embedd Explorer, Faucet, Address Creator into documentation https://github.com/nervosnetwork/docs.nervos.org/pull/253 

**Support**
- [x] How to do this? Docasuarus, Chat, Discrod, Email?  https://github.com/nervosnetwork/docs.nervos.org/pull/242

## Phase 2
**Contracts Examples**
- Update content for contract deployment

**Mining**

**Team:** @RetricSu, @yfeng2824

**Comment by roughpandaz** [comment]
Deployment checklist: https://github.com/nervosnetwork/docs.nervos.org/issues/268

**Comment by roughpandaz** [comment]
Deployed: docs.nervos.org
<img width="1497" alt="Screenshot 2024-04-08 at 12 57 49 PM" src="https://github.com/nervosnetwork/docs.nervos.org/assets/3782456/02c2455b-b4db-4996-87e4-5c343385e86b">
