### ISSUE TITLE
Dev Environment Setup

### ISSUE THREAD

**Issue by roughpandaz** [nervosnetwork/docs.nervos.org#210]
## Context
Setting up the current local dev environment has the following issues:
1. Takes too many steps to setup on all environments
2. Easy to make mistakes and can't debug
3. Requires users to deploy contracts, and create accounts before starting

## Tasks
- [x] Research - how far can we compress dev environment setup (02/23 Fri)
- [x] Reduce setup to 1 single instruction
- [x] Pre-deploy contracts and update state for chain
- [x] Add keys and information into this
- [ ] Future: Add local explorer and other integrations - "Ganache, but better." / Hardhat For CKB

**Comment by RetricSu** [comment]
plan to add this 5 scripts to the local environment.

**Comment by roughpandaz** [comment]
This is built into OffCKB - https://github.com/RetricSu/offckb

**Future:**
- Add local blockexplorer and testing integrations
