### ISSUE TITLE
Docs V2.1.0

### ISSUE THREAD

**Issue by roughpandaz** [nervosnetwork/docs.nervos.org#285]
## V2.1.0

**Home page** @yfeng2824 
- [x] Sections:DApp, Wallet,Concept 
- [x] Node-Operator (@linnnsss check)

**Scripts** @RetricSu 
- [x] Add Scripts (Contracts) tutorial

----------------------------------
## Todos

**Home page** 
- [ ] Comparison information: People here should have some thoughts. Chain Level
- [ ] **All in one page:** Link to all resources → can this be the homepage.

**dApps updates**
- [ ] Tutorial: more real-world documentation

**Scripts**
- [ ] Awesome CKB: https://github.com/aljazceru/awesome-nostr - should this go into ecosystem projects?
- [ ] Add RFC + list of deployed scripts

**Wallet Integrations:**
- [ ] Multi-wallet integration examples
- [ ] Wallet-Connect: check with Lumos
